import { useEffect, useMemo, useState } from 'react';
import { createClient } from '@supabase/supabase-js';
import { Home, Users, Shield, Swords, Trophy, Star, Settings, Flame, Plus, Trash2, RotateCcw, Download, AlertTriangle } from 'lucide-react';

const supabase = createClient(import.meta.env.VITE_SUPABASE_URL, import.meta.env.VITE_SUPABASE_ANON_KEY);
const teamColors=[['Red','🔴','#ef4444'],['Blue','🔵','#38bdf8'],['Green','🟢','#22c55e'],['Yellow','🟡','#facc15'],['Orange','🟠','#fb923c'],['Purple','🟣','#a78bfa'],['Black','⚫','#9ca3af'],['White','⚪','#e5e7eb']];
function combo(players){const out=[];for(let i=0;i<players.length;i++)for(let j=i+1;j<players.length;j++)out.push([players[i],players[j]]);return out}
function validateTeamAsk(playerCount, teamCount){
 if(!teamCount || teamCount<2) return 'You need at least 2 teams to create matches.';
 if(playerCount<4) return 'Unrealistic setup: doubles league needs at least 4 players.';
 if(teamCount>playerCount) return 'Unrealistic setup: number of teams cannot be more than number of players.';
 if(Math.floor(playerCount/teamCount)<2) return `${playerCount} players cannot make ${teamCount} doubles teams. Each team needs at least 2 players.`;
 return '';
}
export default function App(){
 const [tab,setTab]=useState('dashboard'),[mode,setMode]=useState('auto'),[leagues,setLeagues]=useState([]),[weeks,setWeeks]=useState([]),[players,setPlayers]=useState([]),[teams,setTeams]=useState([]),[teamPlayers,setTeamPlayers]=useState([]),[matches,setMatches]=useState([]),[games,setGames]=useState([]),[scores,setScores]=useState([]);
 const [leagueId,setLeagueId]=useState(''),[weekId,setWeekId]=useState(''),[names,setNames]=useState(''),[saving,setSaving]=useState(false),[error,setError]=useState(''),[manual,setManual]=useState({teamCount:4, assignments:{}}),[draft,setDraft]=useState({});
 const league=leagues.find(l=>l.id===leagueId), week=weeks.find(w=>w.id===weekId);
 useEffect(()=>{boot()},[]);
 useEffect(()=>{if(leagueId) loadWeeks(true)},[leagueId]);
 useEffect(()=>{if(weekId) loadWeekData()},[weekId]);
 useEffect(()=>{const d={};scores.forEach(sc=>{d[sc.game_id]={score1:sc.score1??'',score2:sc.score2??''}});setDraft(prev=>({...d,...prev}))},[scores]);
 useEffect(()=>{const ch=supabase.channel('ff-realtime')
  .on('postgres_changes',{event:'*',schema:'public',table:'leagues'},()=>loadLeagues(false))
  .on('postgres_changes',{event:'*',schema:'public',table:'weeks'},()=>loadWeeks(false))
  .on('postgres_changes',{event:'*',schema:'public',table:'players'},()=>loadWeekData())
  .on('postgres_changes',{event:'*',schema:'public',table:'teams'},()=>loadWeekData())
  .on('postgres_changes',{event:'*',schema:'public',table:'team_players'},()=>loadWeekData())
  .on('postgres_changes',{event:'*',schema:'public',table:'matches'},()=>loadWeekData())
  .on('postgres_changes',{event:'*',schema:'public',table:'match_games'},()=>loadWeekData())
  .on('postgres_changes',{event:'*',schema:'public',table:'game_scores'},()=>loadWeekData())
  .subscribe();return()=>supabase.removeChannel(ch)},[leagueId,weekId]);
 function fail(msg){setError(msg); window.scrollTo({top:0,behavior:'smooth'}); return false}
 async function boot(){await loadLeagues(true)}
 async function loadLeagues(selectFirst=true){const {data}=await supabase.from('leagues').select('*').order('created_at'); if(!data?.length){const {data:n}=await supabase.from('leagues').insert({name:"Men's League"}).select().single(); const {data:w}=await supabase.from('weeks').insert({league_id:n.id,name:'Week 1'}).select().single(); setLeagues([n]); setLeagueId(n.id); setWeekId(w.id); return;} setLeagues(data); if(selectFirst&&!leagueId)setLeagueId(data[0].id)}
 async function loadWeeks(selectFirst=true){const {data}=await supabase.from('weeks').select('*').eq('league_id',leagueId).order('created_at'); setWeeks(data||[]); if(selectFirst && data?.length && !data.find(w=>w.id===weekId))setWeekId(data[0].id)}
 async function loadWeekData(){if(!weekId)return; const [p,t,tp,m,g,s]=await Promise.all([supabase.from('players').select('*').eq('week_id',weekId).order('created_at'),supabase.from('teams').select('*').eq('week_id',weekId).order('created_at'),supabase.from('team_players').select('*'),supabase.from('matches').select('*').eq('week_id',weekId).order('slot').order('court'),supabase.from('match_games').select('*'),supabase.from('game_scores').select('*')]); setPlayers(p.data||[]); setTeams(t.data||[]); setTeamPlayers(tp.data||[]); setMatches(m.data||[]); setGames(g.data||[]); setScores(s.data||[])}
 async function act(fn){setError('');setSaving(true); try{await fn(); await loadWeekData();}catch(e){fail(e.message || 'Something went wrong.')}finally{setSaving(false)}}
 function tpForTeam(id){return teamPlayers.filter(x=>x.team_id===id).map(x=>players.find(p=>p.id===x.player_id)).filter(Boolean)}
 function team(id){return teams.find(t=>t.id===id)}
 function scoreFor(gid){return scores.find(s=>s.game_id===gid)||{}}
 async function addPlayers(){const arr=names.split('\n').map(x=>x.trim()).filter(Boolean); if(!arr.length)return fail('Paste at least one player name.'); await act(async()=>{await supabase.from('players').upsert(arr.map(name=>({week_id:weekId,name})),{onConflict:'week_id,name'}); setNames('')})}
 async function removePlayer(p){if(!confirm('Remove player? This may remove related team/game rows.'))return; await act(async()=>supabase.from('players').delete().eq('id',p.id))}
 async function newLeague(){const name=prompt('League name?');if(!name)return; await act(async()=>{const {data:l}=await supabase.from('leagues').insert({name}).select().single(); const {data:w}=await supabase.from('weeks').insert({league_id:l.id,name:'Week 1'}).select().single(); setLeagueId(l.id); setWeekId(w.id)})}
 async function newWeek(){const name=prompt('Week name?',`Week ${weeks.length+1}`);if(!name)return; await act(async()=>{const {data:w}=await supabase.from('weeks').insert({league_id:leagueId,name}).select().single(); setWeekId(w.id)})}
 async function renameWeek(){const name=prompt('Rename week:',week?.name||'');if(!name)return; await act(async()=>{await supabase.from('weeks').update({name}).eq('id',weekId); await loadWeeks(false)})}
 async function deleteWeek(){if(!confirm('Delete week?'))return; await act(async()=>{await supabase.from('weeks').delete().eq('id',weekId); setWeekId('')})}
 async function deleteLeague(){if(!confirm('Delete entire league?'))return; await act(async()=>{await supabase.from('leagues').delete().eq('id',leagueId); setLeagueId(''); setWeekId('')})}
 async function buildTeamsAndSchedule(teamDefs){
   if(teamDefs.some(t=>t.players.length<2)) throw new Error('Every team must have at least 2 players.');
   await supabase.from('teams').delete().eq('week_id',weekId);
   const {data:inserted,error:tErr}=await supabase.from('teams').insert(teamDefs.map((t,i)=>({week_id:weekId,name:t.name,emoji:t.emoji,color:t.color}))).select(); if(tErr) throw tErr;
   const links=[]; teamDefs.forEach((t,i)=>t.players.forEach(p=>links.push({team_id:inserted[i].id,player_id:p.id}))); await supabase.from('team_players').insert(links);
   const matchRows=[]; let slot=1,c=0; for(let i=0;i<inserted.length;i++)for(let j=i+1;j<inserted.length;j++){matchRows.push({week_id:weekId,slot,court:c%2?'B':'A',team1_id:inserted[i].id,team2_id:inserted[j].id}); c++; if(c%2===0)slot++}
   const {data:ms,error:mErr}=await supabase.from('matches').insert(matchRows).select(); if(mErr) throw mErr;
   const teamMap=Object.fromEntries(inserted.map((t,i)=>[t.id,teamDefs[i].players]));
   const gameRows=[]; ms.forEach(m=>{const a=combo(teamMap[m.team1_id]),b=combo(teamMap[m.team2_id]); [0,1,2].forEach(n=>gameRows.push({match_id:m.id,game_number:n+1,t1_player1_id:a[n%a.length][0].id,t1_player2_id:a[n%a.length][1].id,t2_player1_id:b[n%b.length][0].id,t2_player2_id:b[n%b.length][1].id}))}); await supabase.from('match_games').insert(gameRows);
 }
 async function randomTeams(){const count=Number(prompt('Number of teams?',Math.max(2,Math.ceil(players.length/3)))||4); const v=validateTeamAsk(players.length,count); if(v)return fail(v); await act(async()=>{const shuffled=[...players].sort(()=>Math.random()-.5); const defs=Array.from({length:count},(_,i)=>({name:teamColors[i%teamColors.length][0],emoji:teamColors[i%teamColors.length][1],color:teamColors[i%teamColors.length][2],players:[]})); shuffled.forEach((p,i)=>defs[i%count].players.push(p)); await buildTeamsAndSchedule(defs);})}
 function setManualAssign(playerId, teamIndex){setManual(m=>({ ...m, assignments:{...m.assignments, [playerId]: teamIndex} }))}
 async function saveManualTeams(){const count=Number(manual.teamCount); const v=validateTeamAsk(players.length,count); if(v)return fail(v); const assignedIds=Object.keys(manual.assignments).filter(pid=>manual.assignments[pid]!=='' && manual.assignments[pid]!=null); if(assignedIds.length!==players.length) return fail(`Assign all players before saving. ${players.length-assignedIds.length} player(s) are still unassigned.`); const defs=Array.from({length:count},(_,i)=>({name:teamColors[i%teamColors.length][0],emoji:teamColors[i%teamColors.length][1],color:teamColors[i%teamColors.length][2],players:[]})); players.forEach(p=>defs[Number(manual.assignments[p.id])].players.push(p)); const small=defs.find(t=>t.players.length<2); if(small) return fail(`${small.name} has fewer than 2 players. Doubles teams need at least 2.`); await act(async()=>buildTeamsAndSchedule(defs));}
 function draftChange(gameId, side, value){
   if(value!=='' && (Number(value)<0 || Number(value)>99)) return fail('Scores must be between 0 and 99.');
   setError('');
   setDraft(d=>({...d,[gameId]:{score1:d[gameId]?.score1??'',score2:d[gameId]?.score2??'',[side]:value}}));
 }
 async function saveGameScore(gameId){
   const d=draft[gameId]||{}; const s1=d.score1??'', s2=d.score2??'';
   if((s1===''&&s2!=='')||(s1!==''&&s2==='')) return fail('Enter both scores, or clear both scores.');
   await act(async()=>supabase.rpc('update_score_with_history',{p_game_id:gameId,p_score1:s1===''?null:Number(s1),p_score2:s2===''?null:Number(s2)}));
 }
 async function resetGameScore(gameId){
   await act(async()=>{await supabase.rpc('update_score_with_history',{p_game_id:gameId,p_score1:null,p_score2:null}); setDraft(d=>({...d,[gameId]:{score1:'',score2:''}}));});
 }
 async function resetMatchScores(matchId){
   if(!confirm('Reset scores for this match?')) return;
   const ids=games.filter(g=>g.match_id===matchId).map(g=>g.id);
   if(!ids.length) return;
   await act(async()=>{await supabase.from('game_scores').delete().in('game_id',ids); setDraft(d=>{const n={...d}; ids.forEach(id=>n[id]={score1:'',score2:''}); return n;});});
 }
 async function undo(){await act(async()=>supabase.rpc('undo_last_score'))}
 const pName=id=>players.find(p=>p.id===id)?.name||'-';
 const pStats=useMemo(()=>{const st={};players.forEach(p=>st[p.id]={id:p.id,player:p.name,played:0,wins:0,losses:0,pointsFor:0,pointsAgainst:0});games.forEach(g=>{const sc=scoreFor(g.id); if(sc.score1==null||sc.score2==null)return; const a=Number(sc.score1),b=Number(sc.score2); [g.t1_player1_id,g.t1_player2_id].forEach(id=>{if(st[id]){st[id].played++;st[id].pointsFor+=a;st[id].pointsAgainst+=b;if(a>b)st[id].wins++;else if(b>a)st[id].losses++}}); [g.t2_player1_id,g.t2_player2_id].forEach(id=>{if(st[id]){st[id].played++;st[id].pointsFor+=b;st[id].pointsAgainst+=a;if(b>a)st[id].wins++;else if(a>b)st[id].losses++}})}); return Object.values(st).map(x=>({...x,pointDiff:x.pointsFor-x.pointsAgainst,winPct:x.played?Math.round(x.wins/x.played*100):0})).sort((a,b)=>b.wins-a.wins||b.pointDiff-a.pointDiff||b.pointsFor-a.pointsFor||a.player.localeCompare(b.player))},[players,games,scores]);
 const tStats=useMemo(()=>{const st={};teams.forEach(t=>st[t.id]={team:t,played:0,matchWins:0,losses:0,draws:0,gameWins:0,pointsFor:0,pointsAgainst:0});matches.forEach(m=>{let aw=0,bw=0,ap=0,bp=0,done=0;games.filter(g=>g.match_id===m.id).forEach(g=>{const sc=scoreFor(g.id);if(sc.score1==null||sc.score2==null)return;done++;const a=Number(sc.score1),b=Number(sc.score2);ap+=a;bp+=b;if(a>b)aw++;else if(b>a)bw++});const A=st[m.team1_id],B=st[m.team2_id]; if(!A||!B)return; A.gameWins+=aw;B.gameWins+=bw;A.pointsFor+=ap;A.pointsAgainst+=bp;B.pointsFor+=bp;B.pointsAgainst+=ap;if(done){A.played++;B.played++;if(aw>bw){A.matchWins++;B.losses++}else if(bw>aw){B.matchWins++;A.losses++}else{A.draws++;B.draws++}}});return Object.values(st).map(x=>({...x,pointDiff:x.pointsFor-x.pointsAgainst})).sort((a,b)=>b.matchWins-a.matchWins||b.pointDiff-a.pointDiff||b.pointsFor-a.pointsFor)},[teams,matches,games,scores]);
 const completed=scores.filter(s=>s.score1!=null&&s.score2!=null).length;
 const nav=[['dashboard','Dashboard',Home],['players','Players',Users],['teams','Teams',Shield],['matches','Matches',Swords],['team','Team Standings',Trophy],['playersStand','Player Standings',Star],['settings','Settings',Settings]];
 return <div className="app"><aside className="sidebar"><div className="logoBox"><div className="logo">FREAKN<br/><span>FETHRS</span><br/><small>LEAGUE</small></div></div><div className="nav">{nav.map(([k,l,I])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}><I size={20}/>{l}</button>)}</div><div className="card"><b>{saving?'SAVING':'LIVE SYNC'}</b><p className="muted">Errors are shown for unrealistic setups.</p><button className="btn secondary" onClick={undo}><RotateCcw size={16}/> Undo Last Score</button></div></aside><main className="main">{error&&<div className="error"><AlertTriangle size={18}/> {error}</div>}<div className="header"><div><h1>{nav.find(n=>n[0]===tab)?.[1]}</h1><div className="eyebrow">{league?.name||'No League'} · {week?.name||'No Week'}</div></div><div className="row" style={{maxWidth:650}}><select value={leagueId} onChange={e=>{setLeagueId(e.target.value);setWeekId('')}}>{leagues.map(l=><option key={l.id} value={l.id}>{l.name}</option>)}</select><select value={weekId} onChange={e=>setWeekId(e.target.value)}>{weeks.map(w=><option key={w.id} value={w.id}>{w.name}</option>)}</select><button className="btn" onClick={newWeek}><Plus size={16}/> Week</button></div></div>
 {tab==='dashboard'&&<div className="grid stats"><div className="card stat"><Users className="statIcon"/><div><span className="muted">Players</span><b>{players.length}</b></div></div><div className="card stat"><Shield className="statIcon"/><div><span className="muted">Teams</span><b>{teams.length}</b></div></div><div className="card stat"><Swords className="statIcon"/><div><span className="muted">Matches</span><b>{matches.length}</b></div></div><div className="card stat"><Trophy className="statIcon"/><div><span className="muted">Games Completed</span><b>{completed}/{games.length}</b></div></div><div className="card stat"><Flame className="statIcon"/><div><span className="muted">Leader</span><b>{pStats[0]?.player||'-'}</b></div></div></div>}
 {tab==='players'&&<div className="card"><h2>Players</h2><textarea value={names} onChange={e=>setNames(e.target.value)} placeholder="Paste names, one per line"/><button className="btn" onClick={addPlayers}>Add / Import Players</button><table><tbody>{players.map(p=><tr key={p.id}><td>{p.name}</td><td style={{width:120}}><button className="btn danger" onClick={()=>removePlayer(p)}><Trash2 size={16}/></button></td></tr>)}</tbody></table></div>}
 {tab==='teams'&&<div className="card"><h2>Team Setup</h2><div className="row"><button className={mode==='auto'?'btn':'btn secondary'} onClick={()=>setMode('auto')}>Auto Generate</button><button className={mode==='manual'?'btn':'btn secondary'} onClick={()=>setMode('manual')}>Handpick Teams</button></div>{mode==='auto'?<div className="card"><h3>Automatic Team Generator</h3><p className="muted">Shuffles all players and distributes them evenly. Unrealistic requests are blocked.</p><button className="btn" onClick={randomTeams}>Generate Random Teams + Schedule</button></div>:<div className="card"><h3>Manual Team Assignment</h3><div className="row"><label>Number of Teams<input type="number" min="2" max="8" value={manual.teamCount} onChange={e=>setManual({...manual,teamCount:e.target.value})}/></label><button className="btn green" onClick={saveManualTeams}>Save Manual Teams + Schedule</button></div><div className="manualGrid">{Array.from({length:Number(manual.teamCount)||0},(_,i)=><div className="card" key={i}><h3>{teamColors[i%teamColors.length][1]} {teamColors[i%teamColors.length][0]}</h3>{players.map(p=><label className="checkrow" key={p.id}><input type="radio" name={`assign-${p.id}`} checked={Number(manual.assignments[p.id])===i} onChange={()=>setManualAssign(p.id,i)}/>{p.name}</label>)}</div>)}</div></div>}<h2>Current Teams</h2>{teams.map(t=><div className="card" key={t.id} style={{borderLeft:`5px solid ${t.color}`}}><h3>{t.emoji} {t.name}</h3><p>{tpForTeam(t.id).map(p=>p.name).join(', ')}</p></div>)}</div>}
 {tab==='matches'&&<div className="card"><h2>Matches & Scores</h2><p className="muted">Type the full score, then click Save. This prevents fast typing and multi-device overwrite issues.</p>{matches.map(m=><div className="card" key={m.id}><div className="row"><h3>Slot {m.slot} · Court {m.court} · {team(m.team1_id)?.name} vs {team(m.team2_id)?.name}</h3><button className="btn danger" onClick={()=>resetMatchScores(m.id)}>Reset Match Scores</button></div>{games.filter(g=>g.match_id===m.id).sort((a,b)=>a.game_number-b.game_number).map(g=>{const d=draft[g.id]||scoreFor(g.id)||{};return <div className="game" key={g.id}><div>{pName(g.t1_player1_id)} / {pName(g.t1_player2_id)}</div><input className="score" type="number" value={d.score1??''} onChange={e=>draftChange(g.id,'score1',e.target.value)}/><input className="score" type="number" value={d.score2??''} onChange={e=>draftChange(g.id,'score2',e.target.value)}/><div>{pName(g.t2_player1_id)} / {pName(g.t2_player2_id)}</div><div className="row"><button className="btn green" onClick={()=>saveGameScore(g.id)}>Save</button><button className="btn secondary" onClick={()=>resetGameScore(g.id)}>Clear</button></div></div>})}</div>)}</div>}
 {tab==='team'&&<Stand rows={tStats} type="team"/>}{tab==='playersStand'&&<Stand rows={pStats} type="player"/>}
 {tab==='settings'&&<div className="card"><h2>Settings</h2><div className="row"><button className="btn" onClick={newLeague}>Create League</button><button className="btn danger" onClick={deleteLeague}>Delete League</button><button className="btn" onClick={newWeek}>Create Week</button><button className="btn secondary" onClick={renameWeek}>Edit Week Name</button><button className="btn danger" onClick={()=>deleteWeek()}>Delete Week</button></div><div className="row"><button className="btn secondary" onClick={undo}>Undo Last Score</button><button className="btn secondary" onClick={()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify({leagues,weeks,players,teams,teamPlayers,matches,games,scores},null,2)],{type:'application/json'}));a.download='freakn-fethrs-export.json';a.click()}}><Download size={16}/> Export Snapshot</button></div></div>}
 </main></div>}
function Stand({rows,type}){return <div className="card"><h2>Standings</h2><div className="fireline"/>{type==='team'?<table><thead><tr><th>Rank</th><th>Team</th><th>MW</th><th>GW</th><th>PF</th><th>PA</th><th>Diff</th></tr></thead><tbody>{rows.map((s,i)=><tr key={s.team.id}><td>{i+1}</td><td>{s.team.emoji} {s.team.name}</td><td>{s.matchWins}</td><td>{s.gameWins}</td><td>{s.pointsFor}</td><td>{s.pointsAgainst}</td><td className={s.pointDiff>=0?'diffpos':'diffneg'}>{s.pointDiff>0?'+':''}{s.pointDiff}</td></tr>)}</tbody></table>:<table><thead><tr><th>Rank</th><th>Player</th><th>Played</th><th>Wins</th><th>Losses</th><th>PF</th><th>PA</th><th>Diff</th><th>Win %</th></tr></thead><tbody>{rows.map((s,i)=><tr key={s.id}><td>{i===0?'🥇':i===1?'🥈':i===2?'🥉':i+1}</td><td><b>{s.player}</b></td><td>{s.played}</td><td>{s.wins}</td><td>{s.losses}</td><td>{s.pointsFor}</td><td>{s.pointsAgainst}</td><td className={s.pointDiff>=0?'diffpos':'diffneg'}>{s.pointDiff>0?'+':''}{s.pointDiff}</td><td>{s.winPct}%</td></tr>)}</tbody></table>}</div>}
